/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ProjectReviewRouteImport } from './routes/project-review'
import { Route as NexusOpsRouteImport } from './routes/nexus-ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as JobsJobIdRouteImport } from './routes/jobs.$jobId'
import { Route as HistoryRunDirRouteImport } from './routes/history.$runDir'
import { Route as AdminEvaluationRouteImport } from './routes/admin.evaluation'
import { Route as AdminAuditRouteImport } from './routes/admin.audit'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectReviewRoute = ProjectReviewRouteImport.update({
  id: '/project-review',
  path: '/project-review',
  getParentRoute: () => rootRouteImport,
} as any)
const NexusOpsRoute = NexusOpsRouteImport.update({
  id: '/nexus-ops',
  path: '/nexus-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const JobsJobIdRoute = JobsJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => JobsRoute,
} as any)
const HistoryRunDirRoute = HistoryRunDirRouteImport.update({
  id: '/$runDir',
  path: '/$runDir',
  getParentRoute: () => HistoryRoute,
} as any)
const AdminEvaluationRoute = AdminEvaluationRouteImport.update({
  id: '/admin/evaluation',
  path: '/admin/evaluation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/nexus-ops': typeof NexusOpsRoute
  '/project-review': typeof ProjectReviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/history/$runDir': typeof HistoryRunDirRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/nexus-ops': typeof NexusOpsRoute
  '/project-review': typeof ProjectReviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/history/$runDir': typeof HistoryRunDirRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/atlas': typeof AtlasRoute
  '/compare': typeof CompareRoute
  '/dashboard': typeof DashboardRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRouteWithChildren
  '/jobs': typeof JobsRouteWithChildren
  '/login': typeof LoginRoute
  '/nexus-ops': typeof NexusOpsRoute
  '/project-review': typeof ProjectReviewRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/evaluation': typeof AdminEvaluationRoute
  '/history/$runDir': typeof HistoryRunDirRoute
  '/jobs/$jobId': typeof JobsJobIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analyze'
    | '/atlas'
    | '/compare'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/jobs'
    | '/login'
    | '/nexus-ops'
    | '/project-review'
    | '/projects'
    | '/settings'
    | '/admin/audit'
    | '/admin/evaluation'
    | '/history/$runDir'
    | '/jobs/$jobId'
    | '/projects/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analyze'
    | '/atlas'
    | '/compare'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/jobs'
    | '/login'
    | '/nexus-ops'
    | '/project-review'
    | '/projects'
    | '/settings'
    | '/admin/audit'
    | '/admin/evaluation'
    | '/history/$runDir'
    | '/jobs/$jobId'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/atlas'
    | '/compare'
    | '/dashboard'
    | '/health'
    | '/history'
    | '/jobs'
    | '/login'
    | '/nexus-ops'
    | '/project-review'
    | '/projects'
    | '/settings'
    | '/admin/audit'
    | '/admin/evaluation'
    | '/history/$runDir'
    | '/jobs/$jobId'
    | '/projects/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  AtlasRoute: typeof AtlasRoute
  CompareRoute: typeof CompareRoute
  DashboardRoute: typeof DashboardRoute
  HealthRoute: typeof HealthRoute
  HistoryRoute: typeof HistoryRouteWithChildren
  JobsRoute: typeof JobsRouteWithChildren
  LoginRoute: typeof LoginRoute
  NexusOpsRoute: typeof NexusOpsRoute
  ProjectReviewRoute: typeof ProjectReviewRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminEvaluationRoute: typeof AdminEvaluationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-review': {
      id: '/project-review'
      path: '/project-review'
      fullPath: '/project-review'
      preLoaderRoute: typeof ProjectReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nexus-ops': {
      id: '/nexus-ops'
      path: '/nexus-ops'
      fullPath: '/nexus-ops'
      preLoaderRoute: typeof NexusOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/jobs/$jobId': {
      id: '/jobs/$jobId'
      path: '/$jobId'
      fullPath: '/jobs/$jobId'
      preLoaderRoute: typeof JobsJobIdRouteImport
      parentRoute: typeof JobsRoute
    }
    '/history/$runDir': {
      id: '/history/$runDir'
      path: '/$runDir'
      fullPath: '/history/$runDir'
      preLoaderRoute: typeof HistoryRunDirRouteImport
      parentRoute: typeof HistoryRoute
    }
    '/admin/evaluation': {
      id: '/admin/evaluation'
      path: '/admin/evaluation'
      fullPath: '/admin/evaluation'
      preLoaderRoute: typeof AdminEvaluationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface HistoryRouteChildren {
  HistoryRunDirRoute: typeof HistoryRunDirRoute
}

const HistoryRouteChildren: HistoryRouteChildren = {
  HistoryRunDirRoute: HistoryRunDirRoute,
}

const HistoryRouteWithChildren =
  HistoryRoute._addFileChildren(HistoryRouteChildren)

interface JobsRouteChildren {
  JobsJobIdRoute: typeof JobsJobIdRoute
}

const JobsRouteChildren: JobsRouteChildren = {
  JobsJobIdRoute: JobsJobIdRoute,
}

const JobsRouteWithChildren = JobsRoute._addFileChildren(JobsRouteChildren)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  AtlasRoute: AtlasRoute,
  CompareRoute: CompareRoute,
  DashboardRoute: DashboardRoute,
  HealthRoute: HealthRoute,
  HistoryRoute: HistoryRouteWithChildren,
  JobsRoute: JobsRouteWithChildren,
  LoginRoute: LoginRoute,
  NexusOpsRoute: NexusOpsRoute,
  ProjectReviewRoute: ProjectReviewRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminEvaluationRoute: AdminEvaluationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
